package com.hixon.financialApp.model.entity;

import com.hixon.financialApp.utility.Utility;

public class MatchQuery {

    // Fields for MatchQuery
    private String selectQuery;
    private String selectQueryAfterMatch;
    private String matchColumnList;
    private String nameColumn;
    private SearchQualifierProcessor qualifierProcessor;

    public MatchQuery() {
    }

    /**
     * The MatchQuery class represents a query used for matching against a name in natural language mode, boolean mode,
     * or a regular query based on the prefix of the name.  The SQL query should be a select statement that includes
     * everything but the MATCH clause.  A match clause will be appended to the query at runtime with the list of
     * columns to match against, and the user search string substituted in.  Because of this, the query must work with a
     * MATCH clause appended to it, and there must be a full-text index on the table.  The name column should be the
     * name of the column that should be matched against if the user specifies they want an exact match, or LIKE clause,
     * to be used against the primary index.
     *
     * @param selectQuery The SQL SELECT query as a string without the MATCH clause
     * @param nameColumn The name of the column that should be matched against if the exact match or LIKE clause is
     *                   requested
     * @param matchColumnList The list of columns to be used in the MATCH clause as a string
     */
    public MatchQuery(String selectQuery, String nameColumn, String matchColumnList) {
        this.selectQuery = selectQuery;
        this.nameColumn = nameColumn;
        this.matchColumnList = matchColumnList;
        this.selectQueryAfterMatch = "";
        this.qualifierProcessor = SearchQualifierProcessor.IDENTITY;
    }

    /**
     * Enhanced constructor that allows specifying query portions before and after the match conditions.
     * This is useful for adding ORDER BY, LIMIT, or other clauses that should come after WHERE conditions.
     *
     * @param selectQueryBeforeMatch The SQL SELECT query up to and including WHERE with trailing AND
     * @param nameColumn The name of the column that should be matched against if the exact match or LIKE clause is requested
     * @param matchColumnList The list of columns to be used in the MATCH clause as a string
     * @param selectQueryAfterMatch The SQL query portion to append after match conditions (e.g., "ORDER BY column DESC")
     */
    public MatchQuery(String selectQueryBeforeMatch, String nameColumn, String matchColumnList, String selectQueryAfterMatch) {
        this.selectQuery = selectQueryBeforeMatch;
        this.nameColumn = nameColumn;
        this.matchColumnList = matchColumnList;
        this.selectQueryAfterMatch = selectQueryAfterMatch != null ? selectQueryAfterMatch : "";
        this.qualifierProcessor = SearchQualifierProcessor.IDENTITY;
    }

    /**
     * Full constructor that accepts a custom qualifier processor for handling domain-specific
     * search qualifiers like "budget:all:" or "category:expense:".
     *
     * @param selectQueryBeforeMatch The SQL SELECT query up to and including WHERE with trailing AND
     * @param nameColumn The name of the column that should be matched against if the exact match or LIKE clause is requested
     * @param matchColumnList The list of columns to be used in the MATCH clause as a string
     * @param selectQueryAfterMatch The SQL query portion to append after match conditions (e.g., "ORDER BY column DESC")
     * @param qualifierProcessor Processor for handling search qualifiers (budget:all:, category:, etc.)
     */
    public MatchQuery(String selectQueryBeforeMatch, String nameColumn, String matchColumnList,
                      String selectQueryAfterMatch, SearchQualifierProcessor qualifierProcessor) {
        this.selectQuery = selectQueryBeforeMatch;
        this.nameColumn = nameColumn;
        this.matchColumnList = matchColumnList;
        this.selectQueryAfterMatch = selectQueryAfterMatch != null ? selectQueryAfterMatch : "";
        this.qualifierProcessor = qualifierProcessor != null ? qualifierProcessor : SearchQualifierProcessor.IDENTITY;
    }

    /**
     * Helper method to remove trailing AND or WHERE clauses from a SQL query and return all results
     * sorted alphabetically by the name column.
     *
     * @param query The query to process
     * @return The SQL query with trailing AND/WHERE removed and ORDER BY clause added
     */
    private String getAllResultsSortedByName(String query) {
        return query.replaceAll("(?i)\\s+(AND|WHERE)\\s*$", "") + " ORDER BY " + nameColumn + " ASC";
    }

    /**
     * This method takes a name to match against and returns a query that matches against the name
     * in natural language mode, boolean mode, or a regular query based on the prefix of the name.
     * The query is generated by concatenating the name into the query string after stripping the prefix.
     *
     * @param name The name to match against, with a prefix indicating the query type.
     * @return The query string
     */
    public String getQuery(String name) {

        // Process qualifiers FIRST (e.g., "budget:all:", "category:")
        // Do NOT escape here - escape within each branch when constructing SQL
        SearchContext context = qualifierProcessor.process(name, selectQuery);
        String searchTerm = context.getCleanedSearchTerm();
        String modifiedQuery = context.getModifiedQuery();

        // Now process search mode prefixes (n:, b:, e:, l:, s:) with the cleaned term
        if (searchTerm.startsWith("n:")) {
            // Remove the prefix and create a natural language query
            String searchString = searchTerm.substring(2).trim();
            // If search string is empty or only wildcards, return all results sorted alphabetically
            if (searchString.isEmpty() || searchString.replace("*", "").trim().isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }
            String escapedSearchString = Utility.escapeSqlString(searchString);
            return modifiedQuery.replaceFirst("(?i)FROM", ", MATCH(" + matchColumnList + ") AGAINST(\"" + escapedSearchString +
                    "\" IN NATURAL LANGUAGE MODE) as relevance FROM") + " MATCH(" + matchColumnList + ") AGAINST(\"" +
                    escapedSearchString + "\" IN NATURAL LANGUAGE MODE) ORDER BY relevance DESC" +
                    (selectQueryAfterMatch.isEmpty() ? "" : ", " + selectQueryAfterMatch.replaceFirst("(?i)^ORDER BY\\s+", ""));
        } else if (searchTerm.startsWith("b:")) {
            // Remove the prefix and create a boolean mode query
            String searchString = searchTerm.substring(2).trim();
            // If search string is empty, return all results sorted alphabetically
            if (searchString.isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }
            String escapedSearchString = Utility.escapeSqlString(searchString);
            return modifiedQuery + " MATCH(" + matchColumnList + ") AGAINST(\"" + escapedSearchString +
                    "\" IN BOOLEAN MODE)" + addAfterMatchClause();
        } else if (searchTerm.startsWith("e:")) {
            // Remove the prefix and create a regular query
            String searchString = searchTerm.substring(2).trim();
            // If search string is empty, return all results sorted alphabetically
            if (searchString.isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }
            String escapedSearchString = Utility.escapeSqlString(searchString);
            return modifiedQuery + nameColumn + " = \"" + escapedSearchString + "\"" + addAfterMatchClause();
        } else if (searchTerm.startsWith("l:")) {
            // For LIKE pattern match, we assume that '%' wildcards are already provided in the input if needed.
            String searchString = searchTerm.substring(2).trim();
            // If search string is empty, return all results sorted alphabetically
            if (searchString.isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }
            // Escape single quotes by doubling them to prevent SQL syntax errors
            String escapedSearchString = Utility.escapeSqlString(searchString);
            // Wrap OR conditions in parentheses to ensure correct precedence
            StringBuilder likeQuery = new StringBuilder(modifiedQuery);
            likeQuery.append("(");
            String[] columns = matchColumnList.split(",");
            for (int i = 0; i < columns.length; i++) {
                if (i > 0) {
                    likeQuery.append(" OR ");
                }
                likeQuery.append(columns[i].trim()).append(" LIKE '").append(escapedSearchString).append("'");
            }
            likeQuery.append(")");
            likeQuery.append(addAfterMatchClause());
            return likeQuery.toString();
        } else if (searchTerm.startsWith("s:")) {
            // Search mode - wrap search term with wildcards and group OR conditions in parentheses
            String searchString = searchTerm.substring(2).trim();
            // If search string is empty, return all results sorted alphabetically
            if (searchString.isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }
            // Escape single quotes by doubling them to prevent SQL syntax errors
            String escapedSearchString = Utility.escapeSqlString(searchString);
            StringBuilder likeQuery = new StringBuilder(modifiedQuery);
            likeQuery.append("(");
            String[] columns = matchColumnList.split(",");
            for (int i = 0; i < columns.length; i++) {
                if (i > 0) {
                    likeQuery.append(" OR ");
                }
                likeQuery.append(columns[i].trim()).append(" LIKE '%").append(escapedSearchString).append("%'");
            }
            likeQuery.append(")");
            likeQuery.append(addAfterMatchClause());
            return likeQuery.toString();
        } else {
            // Default behavior: simple search mode (wrap search term with wildcards)
            String searchString = searchTerm.trim();
            // If search string is empty or only wildcards/special chars, return all results sorted alphabetically
            if (searchString.isEmpty() || searchString.replace("*", "").replace("%", "").trim().isEmpty()) {
                return getAllResultsSortedByName(modifiedQuery);
            }

            // When the seed is multiple words (e.g. a merchant payee like "ADT SECURITY"), match on
            // the individual words with OR semantics and rank by how many words match, so a partial
            // match such as "ADT Safe Haven" is surfaced for the seed "ADT SECURITY".  This only
            // applies when the caller did not supply its own ORDER BY (selectQueryAfterMatch), so
            // existing ordered searches (e.g. budget-item relevance) are left unchanged.
            if (selectQueryAfterMatch.isEmpty()) {
                String tokenizedQuery = buildTokenizedLikeQuery(modifiedQuery, searchString);
                if (tokenizedQuery != null) {
                    return tokenizedQuery;
                }
            }

            // Escape single quotes by doubling them to prevent SQL syntax errors
            String escapedSearchString = Utility.escapeSqlString(searchString);
            // Build simple LIKE query with wildcards (same as s: prefix)
            StringBuilder likeQuery = new StringBuilder(modifiedQuery);
            likeQuery.append("(");
            String[] columns = matchColumnList.split(",");
            for (int i = 0; i < columns.length; i++) {
                if (i > 0) {
                    likeQuery.append(" OR ");
                }
                likeQuery.append(columns[i].trim()).append(" LIKE '%").append(escapedSearchString).append("%'");
            }
            likeQuery.append(")");
            likeQuery.append(addAfterMatchClause());
            return likeQuery.toString();
        }
    }

    /**
     * Common noise words that should not, on their own, broaden a multi-word "any word matches"
     * search.  Kept intentionally small — only words that appear in a large fraction of names.
     */
    private static final java.util.Set<String> SEARCH_STOPWORDS = java.util.Set.of(
            "THE", "AND", "OF", "FOR", "COM", "LLC", "INC", "CO");

    /**
     * Payment-processor prefixes and other short tokens that should not contribute to the
     * tokenized search score.  These prefixes appear in bank descriptors (e.g. "PY *PRODIGY",
     * "GOOGLE *YouTube TV", "AMAZON MKTPL*...") and would otherwise match many unrelated
     * merchant names as substrings.
     */
    private static final java.util.Set<String> PAYMENT_PROCESSOR_NOISE = java.util.Set.of(
            "PY", "SQ", "TST", "SP", "WP", "UEP", "ACH", "POS", "DEBIT", "CREDIT", "CHECKCARD",
            "GOOGLE", "AMAZON", "MKTPL", "MKTPLACE", "PRIME", "PAYPAL", "VENMO", "ZELLE");

    /**
     * Builds a tokenized LIKE query for a multi-word search seed.  Every meaningful word is matched
     * with OR semantics against every match column, and the results are ordered by the number of
     * words that match (most matches first).  This surfaces partial matches — e.g. the seed
     * "ADT SECURITY" finds the merchant "ADT Safe Haven" (which matches on "ADT") — that a single
     * whole-phrase {@code LIKE '%ADT SECURITY%'} would miss.
     *
     * @param modifiedQuery the SELECT ... WHERE query (ending with "WHERE " or "... AND ")
     * @param searchString  the raw multi-word search seed
     * @return the tokenized query, or {@code null} if the seed has fewer than two meaningful words
     *         (in which case the caller should fall back to the single-phrase LIKE behavior)
     */
    private String buildTokenizedLikeQuery(String modifiedQuery, String searchString) {
        String[] rawWords = searchString.trim().split("\\s+");
        java.util.List<String> words = new java.util.ArrayList<>();
        for (String rawWord : rawWords) {
            String cleaned = rawWord.replace("%", "").replace("*", "").trim();
            if (cleaned.length() >= 3 && !SEARCH_STOPWORDS.contains(cleaned.toUpperCase())
                    && !PAYMENT_PROCESSOR_NOISE.contains(cleaned.toUpperCase())) {
                words.add(cleaned);
            }
        }
        // Only worthwhile when there are at least two meaningful words; otherwise the single-phrase
        // LIKE is equivalent and simpler.
        if (words.size() < 2) {
            return null;
        }

        String[] columns = matchColumnList.split(",");
        StringBuilder query = new StringBuilder(modifiedQuery);

        // WHERE ( any word matches any column )
        query.append("(");
        boolean first = true;
        for (String word : words) {
            String escaped = Utility.escapeSqlString(word);
            for (String column : columns) {
                if (!first) {
                    query.append(" OR ");
                }
                query.append(column.trim()).append(" LIKE '%").append(escaped).append("%'");
                first = false;
            }
        }
        query.append(")");

        // ORDER BY: prioritize matches on the first (main) word, then sum all matches.
        // Tiebreaker: when first-word scores are equal, prefer exact match on first word only,
        // then shorter names (fewer extra words).  This ensures "COSTCO" ranks above "Costco Gas
        // Station" when both match the first word equally.
        String firstWordEscaped = Utility.escapeSqlString(words.get(0));
        query.append(" ORDER BY (");
        first = true;
        // Boost first-word matches (they get higher priority in the sum)
        for (String column : columns) {
            if (!first) {
                query.append(" + ");
            }
            query.append("(").append(column.trim()).append(" LIKE '%").append(firstWordEscaped).append("%') * 10");
            first = false;
        }
        // Then add matching on other words (lower priority)
        for (int i = 1; i < words.size(); i++) {
            String escaped = Utility.escapeSqlString(words.get(i));
            for (String column : columns) {
                query.append(" + ");
                query.append("(").append(column.trim()).append(" LIKE '%").append(escaped).append("%')");
            }
        }
        query.append(") DESC, ");
        // Tiebreaker 1: exact match on first word (case-insensitive) gets highest priority
        first = true;
        for (String column : columns) {
            if (!first) {
                query.append(" OR ");
            }
            query.append("(").append(column.trim()).append(" = \"").append(firstWordEscaped).append("\")");
            first = false;
        }
        query.append(" DESC, ");
        // Tiebreaker 2: shorter names (fewer extra words) rank higher when primary score and exact match tie
        query.append("LENGTH(").append(columns[0].trim()).append(") ASC");

        return query.toString();
    }

    /**
     * Helper method to add the selectQueryAfterMatch clause with proper spacing.
     *
     * @return The selectQueryAfterMatch with a leading space, or empty string if not set
     */
    private String addAfterMatchClause() {
        return selectQueryAfterMatch.isEmpty() ? "" : " " + selectQueryAfterMatch;
    }

    /**
     *  Method to check the string for specified patterns from the SQL LIKE clause and the MySQL boolean mode operators.
     *  The method checks if the string starts with "b:" and contains boolean mode operators or starts with "l:" and
     *  contains SQL LIKE wildcards. The method returns true if the string meets any of the criteria, otherwise it
     *  returns false.
     *  @param input The string to check for patterns
     *  @return true if the string meets any of the criteria, otherwise false
     */
    public static boolean checkStringPattern(String input) {
        if (input == null || input.length() < 3) {
            // Early return if input is null or too short to meet the criteria
            return false;
        }

        // Check if string starts with "b:" and contains boolean mode operators
        if (input.startsWith("b:")) {
            String checkPart = input.substring(2); // Remove the prefix
            // Regex to find any boolean mode operator
            String booleanModeOperators = "[\\+\\-\\>\\<\\(\\)\\~\\*\\\"]";
            return checkPart.matches(".*" + booleanModeOperators + ".*");
        }

        // Check if string starts with "l:" and contains LIKE wildcards
        if (input.startsWith("l:")) {
            String checkPart = input.substring(2); // Remove the prefix
            // Regex to find any SQL LIKE wildcard
            String likeWildcards = "[%_]";
            return checkPart.matches(".*" + likeWildcards + ".*");
        }

        // Check if string starts with "s:":
        if (input.startsWith("s:")) {
             return true;
        }


        // Return false if none of the conditions are met
        return false;
    }


    /**
     * This method takes a string to match against that may contain a prefix indicating the query type.
     * n: for natural language mode, b: for boolean mode, or e: for a regular query based on the prefix of the name.
     * This method strips off the prefix and returns the cleaned string.
     *
     * @param name The name to match against, with a prefix indicating the query type.
     * @return The query string
     */
    public String cleanName(String name) {

        // Remove the prefix and any wildcards from the name and return:
        if (name.startsWith("n:")) {
            return name.substring(2);
        } else if (name.startsWith("b:")) {
            name = name.replace("*", "");
            name = name.replace("+", "");
            name = name.replace("-", "");
            name = name.replace("\"", "");
            name = name.replace("~", "");
            name = name.replace("<", "");
            name = name.replace(">", "");
            name = name.replace("(", "");
            name = name.replace(")", "");
            name = name.replace("\"", "");
            return name.substring(2);
        } else if (name.startsWith("e:")) {
            return name.substring(2);
        } else if (name.startsWith("l:")) {
            // For LIKE queries, strip the prefix and any surrounding quotes, but keep wildcards (% and _)
            String cleaned = name.substring(2);
            // Remove surrounding quotes if present
            if (cleaned.startsWith("\"") && cleaned.endsWith("\"") && cleaned.length() > 1) {
                cleaned = cleaned.substring(1, cleaned.length() - 1);
            }
            return cleaned;
        } else {
            return name;
        }
    }

    /**
     * Gets the list of columns that are searched in this match query.
     *
     * @return The comma-separated list of column names
     */
    public String getMatchColumnList() {
        return matchColumnList;
    }

    /**
     * Gets a user-friendly description of the searchable fields.
     * Converts database column names to readable field names.
     *
     * @return A formatted string describing searchable fields (e.g., "name, category, payee, memo")
     */
    public String getSearchableFieldsDescription() {
        if (matchColumnList == null || matchColumnList.isEmpty()) {
            return "name";
        }

        // Clean up column names for user display
        String[] columns = matchColumnList.split(",");
        StringBuilder description = new StringBuilder();

        for (int i = 0; i < columns.length; i++) {
            String column = columns[i].trim();

            // Remove table prefixes and convert to user-friendly names
            if (column.contains(".")) {
                column = column.substring(column.lastIndexOf(".") + 1);
            }

            // Convert common column names to user-friendly terms
            column = column.toLowerCase()
                    .replace("_", " ")
                    .replace("budgetitemname", "name")
                    .replace("merchantname", "name")
                    .replace("categoryname", "category")
                    .replace("payeename", "payee");

            if (i > 0) {
                description.append(", ");
            }
            description.append(column);
        }

        return description.toString();
    }
}
