package com.hixon.financialApp.view.text;

import com.hixon.financialApp.controller.ControllerException;
import com.hixon.financialApp.model.budget.BudgetException;
import com.hixon.financialApp.model.entity.Entity;
import com.hixon.financialApp.model.entity.EntityException;
import com.hixon.financialApp.model.forecast.Forecast;
import com.hixon.financialApp.model.forecast.ForecastException;
import com.hixon.financialApp.model.forecast.ForecastTransaction;
import com.hixon.financialApp.model.user.User;
import com.hixon.financialApp.view.ViewException;
import com.hixon.financialApp.view.base.AbstractForecastView;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;

/**
 * The {@link ForecastView} class in the text package contains all the logic common and particular to text based ways of
 * viewing the forecast.  The exception is formatting text based reports on the forecast which is done in the
 * {@link ForecastReport} class in the text package because the generic reporting architecture
 * {@link com.hixon.financialApp.view.base.Renderer} requires that reports extend
 * {@link com.hixon.financialApp.view.base.ViewReportInt}.  However, reports that are not generated by the
 * {@link com.hixon.financialApp.view.base.Renderer} would be generated here.  For example generating a text based
 * version of the forecast.
 */
public class ForecastView extends AbstractForecastView {

    public ForecastView(Forecast forecast) {
        super(forecast);
    }

    @Override
    protected void openLongTermForecastOutput() throws FileNotFoundException, UnsupportedEncodingException {

    }

    @Override
    protected void renderLongTermForecastFrontMatter() {

    }

    @Override
    protected void renderMonthHeader(Calendar plannedDate, double runningBalance) {

    }

    @Override
    protected void renderForecastTransaction(ForecastTransaction forecastTransaction, double credit, double debit)
            throws EntityException, SQLException, ForecastException, BudgetException {

    }

    @Override
    protected void renderLongTermForecastBackMatter() {

    }

    @Override
    protected void closeLongTermForecastOutput() {

    }

    @Override
    protected void closeForecastTransactionSource() throws ViewException {

    }

    @Override
    protected List<ForecastTransaction> openForecastTransactionSource() throws IOException, ControllerException,
            BudgetException {
        return null;
    }

    @Override
    protected TrackingItemsOfInterestReport getTrackingItemsOfInterestReport(User user, List<Entity> items, File reportFile)
            throws FileNotFoundException {
        return new TrackingItemsOfInterestReport(forecast, user, items, reportFile);
    }

    @Override
    protected UpcomingItemsOfInterestReport getUpcomingItemsOfInterestReport(User user, List<Entity> items, File reportFile)
            throws FileNotFoundException {
        return new UpcomingItemsOfInterestReport(forecast, user, items, reportFile);
    }

    @Override
    public OverdueItemsReport getOverdueItemsReport(Forecast forecast, List<Entity> items, File reportFile)
            throws FileNotFoundException {
        return new com.hixon.financialApp.view.text.OverdueItemsReport(forecast, items, reportFile);
    }

    @Override
    public UpcomingItemsReport getUpcomingItemsReport(Forecast forecast, List<Entity> items, File reportFile)
            throws FileNotFoundException {
        return new UpcomingItemsReport(forecast, items, reportFile);
    }
}
